(function () {
  "use strict";

  const stageDefinitions = {
    primary: {
      title: "Primary assessment",
      help: "Start with quick safety and response checks before jumping into treatment.",
    },
    abc: {
      title: "ABC / life threats",
      help: "Look for breathing problems, severe bleeding, and obvious life threats.",
    },
    help: {
      title: "Help / EMS / equipment",
      help: "Bring in help and equipment when the situation is serious or might get worse.",
    },
    treatment: {
      title: "Treatment",
      help: "Choose the care that fits what is happening in this scenario.",
    },
    ongoing: {
      title: "Secondary assessment / ongoing care",
      help: "After the main problem is handled, keep checking and supporting the person.",
    },
    submit: {
      title: "Submit",
      help: "Review your order. If it looks right, submit it for feedback.",
    },
  };

  const actions = {
    scene_safety: {
      label: "Check scene safety",
      detail: "Make sure the area is safe before getting hands-on.",
      type: "assessment",
    },
    ppe_barriers: {
      label: "Use PPE / barrier precautions",
      detail: "Use gloves or a barrier if available.",
      type: "assessment",
    },
    check_responsiveness: {
      label: "Check responsiveness",
      detail: "See if they respond to voice or touch.",
      type: "assessment",
    },
    check_airway_breathing: {
      label: "Check airway and breathing",
      detail: "Decide if breathing is normal or not.",
      type: "assessment",
    },
    check_severe_bleeding: {
      label: "Check for severe bleeding",
      detail: "Look fast for bleeding that needs immediate pressure.",
      type: "assessment",
    },
    check_circulation_life_threats: {
      label: "Check circulation / obvious life threats",
      detail: "Scan for pale skin, shock signs, major injury, or danger signs.",
      type: "assessment",
    },
    call_ems_911: {
      label: "Call EMS / 911",
      detail: "Get emergency help started.",
      type: "help",
    },
    get_aed: {
      label: "Get AED",
      detail: "Bring the AED when a breathing/cardiac emergency is possible.",
      type: "help",
    },
    get_first_aid_kit: {
      label: "Get first aid kit",
      detail: "Bring dressings, gloves, and basic supplies.",
      type: "help",
    },
    get_backup: {
      label: "Get backup / notify lifeguard team",
      detail: "Get another trained person helping.",
      type: "help",
    },
    cpr_aed: {
      label: "Start CPR / use AED",
      detail: "Use when the person is unresponsive and not breathing normally.",
      type: "treatment",
    },
    recovery_position_airway: {
      label: "Recovery position / keep airway open",
      detail: "For an unresponsive person who is breathing.",
      type: "treatment",
    },
    firm_direct_pressure: {
      label: "Apply firm direct pressure",
      detail: "Use strong pressure on severe bleeding.",
      type: "treatment",
    },
    light_pressure_pad: {
      label: "Put pad on wound lightly",
      detail: "A weak bleeding-control choice.",
      type: "treatment",
      quality: "weak",
    },
    maintain_pressure: {
      label: "Maintain pressure / add dressing",
      detail: "Keep pressure on and reinforce if needed.",
      type: "treatment",
    },
    remove_pressure_early: {
      label: "Remove pressure to check bleeding",
      detail: "Can restart bleeding if done too early.",
      type: "treatment",
      quality: "danger",
    },
    treat_shock_monitor: {
      label: "Treat for shock / monitor",
      detail: "Keep them still, supported, and watched.",
      type: "treatment",
    },
    support_immobilize_injury: {
      label: "Support and immobilize injury",
      detail: "Support the injured part and limit movement.",
      type: "treatment",
    },
    cool_burn_water: {
      label: "Cool burn with cool clean water",
      detail: "Cool the burn instead of adding random products.",
      type: "treatment",
    },
    cover_burn_loosely: {
      label: "Cover burn loosely",
      detail: "Protect it without tight pressure.",
      type: "treatment",
    },
    ice_direct_burn: {
      label: "Apply ice directly to burn",
      detail: "A bad burn-care choice.",
      type: "treatment",
      quality: "danger",
    },
    pop_blisters_creams: {
      label: "Pop blisters / apply random creams",
      detail: "A bad burn-care choice.",
      type: "treatment",
      quality: "danger",
    },
    move_cooler_area: {
      label: "Move to cooler area",
      detail: "Get them out of the heat if safe.",
      type: "treatment",
    },
    fan_only: {
      label: "Place beside fan only",
      detail: "Not enough for suspected heat stroke.",
      type: "treatment",
      quality: "weak",
    },
    loosen_heavy_gear: {
      label: "Loosen/remove heavy gear",
      detail: "Remove heat-trapping layers or gear if safe.",
      type: "treatment",
    },
    wet_skin_fan: {
      label: "Wet skin/clothing and fan",
      detail: "Active cooling for serious heat illness.",
      type: "treatment",
    },
    cold_packs_core: {
      label: "Apply cold packs to core areas",
      detail: "Cooling support for severe heat illness.",
      type: "treatment",
    },
    sips_fluid_awake: {
      label: "Give small sips if awake/able",
      detail: "Only if awake, able to swallow, and the scenario fits.",
      type: "treatment",
    },
    water_unresponsive: {
      label: "Give water to an unresponsive victim",
      detail: "Dangerous because they may not swallow safely.",
      type: "treatment",
      quality: "danger",
    },
    cpr_while_breathing: {
      label: "Start CPR while victim is breathing",
      detail: "Wrong care if normal breathing is present.",
      type: "treatment",
      quality: "danger",
    },
    keep_still_spinal: {
      label: "Keep still / spinal precautions",
      detail: "Use when head, neck, or spine injury is possible.",
      type: "treatment",
    },
    move_spinal_unnecessary: {
      label: "Move suspected spinal victim unnecessarily",
      detail: "Can make a head/neck/spine injury worse.",
      type: "treatment",
      quality: "danger",
    },
    treat_visible_before_breathing: {
      label: "Treat visible injury before breathing check",
      detail: "A priority mistake in serious scenarios.",
      type: "treatment",
      quality: "weak",
    },
    leave_alone: {
      label: "Leave victim alone",
      detail: "They still need monitoring.",
      type: "ongoing",
      quality: "danger",
    },
    head_to_toe: {
      label: "Do a head-to-toe check",
      detail: "Look for other injuries after urgent issues are handled.",
      type: "ongoing",
    },
    check_skin: {
      label: "Check skin condition",
      detail: "Notice pale, hot, cool, clammy, or changing skin.",
      type: "ongoing",
    },
    pulse_breathing_rate: {
      label: "Check pulse and breathing rate",
      detail: "Track whether they are improving or getting worse.",
      type: "ongoing",
    },
    ask_sample: {
      label: "Ask SAMPLE/history questions",
      detail: "Ask simple history questions if they can answer.",
      type: "ongoing",
    },
    reassess_treatment: {
      label: "Reassess treatment",
      detail: "Check whether your care is actually working.",
      type: "ongoing",
    },
    monitor_until_help: {
      label: "Keep monitoring until help arrives",
      detail: "Stay with them and keep reassessing.",
      type: "ongoing",
    },
  };

  function stage(id, choices) {
    return {
      id,
      title: stageDefinitions[id].title,
      help: stageDefinitions[id].help,
      choices: choices || [],
    };
  }

  function withSubmit(stages) {
    return stages.concat(stage("submit", []));
  }

  function labelsFor(actionIds) {
    return actionIds.map((id, index) => `${index + 1}. ${actions[id].label}`).join("\n");
  }

  const commonPrimary = ["scene_safety", "ppe_barriers", "check_responsiveness"];
  const commonHelp = ["call_ems_911", "get_aed", "get_first_aid_kit", "get_backup"];
  const commonOngoing = [
    "head_to_toe",
    "check_skin",
    "pulse_breathing_rate",
    "ask_sample",
    "reassess_treatment",
    "monitor_until_help",
    "leave_alone",
  ];

  const scenarios = [
    {
      id: "severe_external_bleeding",
      title: "Severe external bleeding",
      prompt:
        "A patron slips near a broken tile and has heavy bleeding from the lower leg. They are awake, scared, and bleeding through a towel.",
      stages: withSubmit([
        stage("primary", commonPrimary),
        stage("abc", ["check_airway_breathing", "check_severe_bleeding", "check_circulation_life_threats"]),
        stage("help", commonHelp),
        stage("treatment", [
          "firm_direct_pressure",
          "light_pressure_pad",
          "maintain_pressure",
          "remove_pressure_early",
          "treat_shock_monitor",
          "treat_visible_before_breathing",
        ]),
        stage("ongoing", commonOngoing),
      ]),
      recommendedSequence: [
        "scene_safety",
        "ppe_barriers",
        "check_responsiveness",
        "check_airway_breathing",
        "check_severe_bleeding",
        "firm_direct_pressure",
        "call_ems_911",
        "get_backup",
        "maintain_pressure",
        "treat_shock_monitor",
        "reassess_treatment",
        "monitor_until_help",
      ],
      criticalActions: [
        "scene_safety",
        "check_airway_breathing",
        "check_severe_bleeding",
        "firm_direct_pressure",
        "call_ems_911",
        "maintain_pressure",
        "monitor_until_help",
      ],
      weakActions: ["light_pressure_pad", "treat_visible_before_breathing"],
      dangerousActions: ["remove_pressure_early", "leave_alone"],
      optionalGoodActions: [
        "ppe_barriers",
        "get_backup",
        "get_first_aid_kit",
        "treat_shock_monitor",
        "reassess_treatment",
      ],
      actionFeedback: {
        check_severe_bleeding: "The bleeding is heavy and needs immediate control.",
        firm_direct_pressure: "Bleeding starts to slow under firm pressure.",
        light_pressure_pad: "The bleeding is still soaking through.",
        maintain_pressure: "Pressure stays on and the dressing is reinforced.",
        remove_pressure_early: "The bleeding gets worse when pressure comes off.",
      },
      suggestedOrderText: "",
      hints: {
        primary: "Do not skip the basic safety check.",
        abc: "This person is awake, but the bleeding is still a life threat.",
        help: "Heavy bleeding is a good time to get help moving.",
        treatment: "Light pressure is not enough for this one.",
        ongoing: "After pressure is on, keep checking that it is working.",
      },
      tags: ["bleeding", "awake", "life threat"],
    },
    {
      id: "severe_bleeding_weak_pressure",
      title: "Severe bleeding with weak pressure mistake",
      prompt:
        "A patron has a deep forearm cut from pool equipment. The bleeding is heavy. Someone suggests just holding a small tissue lightly on the cut.",
      stages: withSubmit([
        stage("primary", commonPrimary),
        stage("abc", ["check_airway_breathing", "check_severe_bleeding", "check_circulation_life_threats"]),
        stage("help", commonHelp),
        stage("treatment", [
          "light_pressure_pad",
          "firm_direct_pressure",
          "maintain_pressure",
          "remove_pressure_early",
          "treat_shock_monitor",
        ]),
        stage("ongoing", commonOngoing),
      ]),
      recommendedSequence: [
        "scene_safety",
        "ppe_barriers",
        "check_responsiveness",
        "check_airway_breathing",
        "check_severe_bleeding",
        "firm_direct_pressure",
        "maintain_pressure",
        "call_ems_911",
        "get_first_aid_kit",
        "treat_shock_monitor",
        "reassess_treatment",
        "monitor_until_help",
      ],
      criticalActions: [
        "scene_safety",
        "check_severe_bleeding",
        "firm_direct_pressure",
        "maintain_pressure",
        "call_ems_911",
        "monitor_until_help",
      ],
      weakActions: ["light_pressure_pad"],
      dangerousActions: ["remove_pressure_early", "leave_alone"],
      optionalGoodActions: [
        "ppe_barriers",
        "check_airway_breathing",
        "get_first_aid_kit",
        "get_backup",
        "treat_shock_monitor",
        "reassess_treatment",
      ],
      actionFeedback: {
        check_severe_bleeding: "The cut is bleeding heavily.",
        light_pressure_pad: "The bleeding is still soaking through.",
        firm_direct_pressure: "Firm pressure begins to control the bleeding.",
        maintain_pressure: "The dressing is reinforced without lifting pressure.",
        remove_pressure_early: "The bleeding restarts when pressure is removed.",
      },
      suggestedOrderText: "",
      hints: {
        primary: "The bad suggestion is a distraction. Start normally.",
        abc: "Name the life threat before treating it.",
        help: "A second person can call and bring supplies while pressure stays on.",
        treatment: "Choose the pressure option that actually controls heavy bleeding.",
        ongoing: "Do not keep peeling dressings back to inspect.",
      },
      tags: ["bleeding", "weak treatment", "pressure"],
    },
    {
      id: "unresponsive_not_breathing",
      title: "Unresponsive and not breathing normally",
      prompt:
        "A patron collapses on the pool deck. They do not respond when you speak to them, and they are not breathing normally.",
      stages: withSubmit([
        stage("primary", commonPrimary),
        stage("abc", ["check_airway_breathing", "check_severe_bleeding", "check_circulation_life_threats"]),
        stage("help", commonHelp),
        stage("treatment", [
          "cpr_aed",
          "recovery_position_airway",
          "water_unresponsive",
          "treat_visible_before_breathing",
        ]),
        stage("ongoing", ["pulse_breathing_rate", "reassess_treatment", "monitor_until_help", "leave_alone"]),
      ]),
      recommendedSequence: [
        "scene_safety",
        "ppe_barriers",
        "check_responsiveness",
        "check_airway_breathing",
        "call_ems_911",
        "get_aed",
        "cpr_aed",
        "reassess_treatment",
        "monitor_until_help",
      ],
      criticalActions: [
        "scene_safety",
        "check_responsiveness",
        "check_airway_breathing",
        "call_ems_911",
        "get_aed",
        "cpr_aed",
      ],
      weakActions: ["recovery_position_airway", "treat_visible_before_breathing"],
      dangerousActions: ["water_unresponsive", "leave_alone"],
      optionalGoodActions: ["ppe_barriers", "get_backup", "check_severe_bleeding", "monitor_until_help"],
      actionFeedback: {
        check_responsiveness: "They do not respond.",
        check_airway_breathing: "You do not see normal breathing.",
        call_ems_911: "Emergency help is being called.",
        get_aed: "The AED is on the way.",
        cpr_aed: "You start CPR/AED care.",
        recovery_position_airway: "That would fit better if they were breathing normally.",
        water_unresponsive: "They cannot safely swallow while unresponsive.",
      },
      suggestedOrderText: "",
      hints: {
        primary: "Find out if they respond before picking treatment.",
        abc: "The breathing check drives the big decision here.",
        help: "This is an AED/EMS scenario.",
        treatment: "Not breathing normally changes the care choice.",
        ongoing: "Keep reassessing after starting care.",
      },
      tags: ["unresponsive", "not breathing", "aed"],
    },
    {
      id: "unresponsive_breathing",
      title: "Unresponsive but breathing",
      prompt:
        "A patron is lying on the deck after feeling dizzy. They do not respond, but you find they are breathing normally.",
      stages: withSubmit([
        stage("primary", commonPrimary),
        stage("abc", ["check_airway_breathing", "check_severe_bleeding", "check_circulation_life_threats"]),
        stage("help", commonHelp),
        stage("treatment", ["recovery_position_airway", "cpr_while_breathing", "cpr_aed", "water_unresponsive"]),
        stage("ongoing", ["pulse_breathing_rate", "reassess_treatment", "monitor_until_help", "leave_alone"]),
      ]),
      recommendedSequence: [
        "scene_safety",
        "ppe_barriers",
        "check_responsiveness",
        "check_airway_breathing",
        "call_ems_911",
        "recovery_position_airway",
        "get_backup",
        "pulse_breathing_rate",
        "monitor_until_help",
      ],
      criticalActions: [
        "scene_safety",
        "check_responsiveness",
        "check_airway_breathing",
        "call_ems_911",
        "recovery_position_airway",
        "monitor_until_help",
      ],
      weakActions: ["cpr_aed"],
      dangerousActions: ["cpr_while_breathing", "water_unresponsive", "leave_alone"],
      optionalGoodActions: ["ppe_barriers", "get_backup", "get_aed", "pulse_breathing_rate", "reassess_treatment"],
      actionFeedback: {
        check_responsiveness: "They still do not respond.",
        check_airway_breathing: "They are breathing normally.",
        recovery_position_airway: "Their airway is being kept open while you monitor them.",
        cpr_while_breathing: "They are breathing, so CPR is the wrong move here.",
        water_unresponsive: "They cannot safely swallow while unresponsive.",
      },
      suggestedOrderText: "",
      hints: {
        primary: "Do the same opening checks even if the story sounds obvious.",
        abc: "Breathing normally changes the treatment.",
        help: "Unresponsive still means you should get help.",
        treatment: "Do not choose CPR just because they are unresponsive.",
        ongoing: "Breathing can change, so keep checking.",
      },
      tags: ["unresponsive", "breathing", "airway"],
    },
    {
      id: "suspected_fracture",
      title: "Suspected fracture",
      prompt:
        "A patron slips while walking and lands on their arm. They are awake, breathing normally, and their forearm looks deformed and painful.",
      stages: withSubmit([
        stage("primary", commonPrimary),
        stage("abc", ["check_airway_breathing", "check_severe_bleeding", "check_circulation_life_threats"]),
        stage("help", commonHelp),
        stage("treatment", [
          "support_immobilize_injury",
          "firm_direct_pressure",
          "cpr_aed",
          "treat_visible_before_breathing",
        ]),
        stage("ongoing", commonOngoing),
      ]),
      recommendedSequence: [
        "scene_safety",
        "ppe_barriers",
        "check_responsiveness",
        "check_airway_breathing",
        "check_severe_bleeding",
        "support_immobilize_injury",
        "get_first_aid_kit",
        "get_backup",
        "reassess_treatment",
        "monitor_until_help",
      ],
      criticalActions: [
        "scene_safety",
        "check_responsiveness",
        "check_airway_breathing",
        "check_severe_bleeding",
        "support_immobilize_injury",
        "reassess_treatment",
      ],
      weakActions: ["firm_direct_pressure", "cpr_aed", "treat_visible_before_breathing"],
      dangerousActions: ["leave_alone"],
      optionalGoodActions: ["ppe_barriers", "get_first_aid_kit", "get_backup", "ask_sample", "monitor_until_help"],
      actionFeedback: {
        check_airway_breathing: "They are breathing normally.",
        check_severe_bleeding: "No severe bleeding is found.",
        support_immobilize_injury: "The arm is supported and movement is reduced.",
        firm_direct_pressure: "There is no heavy bleeding to control.",
        treat_visible_before_breathing: "You may be skipping basic life-threat checks.",
      },
      suggestedOrderText: "",
      hints: {
        primary: "Visible injury still comes after quick safety and response checks.",
        abc: "Confirm there is no immediate life threat.",
        help: "Supplies and backup can help with supporting the arm.",
        treatment: "The key treatment is support and less movement.",
        ongoing: "Ask what happened and keep reassessing pain and circulation signs.",
      },
      tags: ["fracture", "arm", "awake"],
    },
    {
      id: "minor_moderate_burn",
      title: "Minor/moderate burn",
      prompt:
        "A patron touches hot metal near the pool deck and has a painful red burn with small blisters on the hand. They are awake and breathing normally.",
      stages: withSubmit([
        stage("primary", commonPrimary),
        stage("abc", ["check_airway_breathing", "check_severe_bleeding", "check_circulation_life_threats"]),
        stage("help", commonHelp),
        stage("treatment", ["cool_burn_water", "cover_burn_loosely", "ice_direct_burn", "pop_blisters_creams"]),
        stage("ongoing", commonOngoing),
      ]),
      recommendedSequence: [
        "scene_safety",
        "ppe_barriers",
        "check_responsiveness",
        "check_airway_breathing",
        "cool_burn_water",
        "cover_burn_loosely",
        "get_first_aid_kit",
        "reassess_treatment",
        "monitor_until_help",
      ],
      criticalActions: ["scene_safety", "cool_burn_water", "cover_burn_loosely", "reassess_treatment"],
      weakActions: ["firm_direct_pressure"],
      dangerousActions: ["ice_direct_burn", "pop_blisters_creams", "leave_alone"],
      optionalGoodActions: [
        "ppe_barriers",
        "check_responsiveness",
        "check_airway_breathing",
        "get_first_aid_kit",
        "get_backup",
        "monitor_until_help",
      ],
      actionFeedback: {
        cool_burn_water: "The burn is being cooled with clean cool water.",
        cover_burn_loosely: "The burn is protected without tight pressure.",
        ice_direct_burn: "The skin reacts badly to direct ice.",
        pop_blisters_creams: "The burn area is being irritated instead of protected.",
      },
      suggestedOrderText: "",
      hints: {
        primary: "Even small burns start with a safe scene.",
        abc: "This is not mainly an airway/breathing emergency, but check basics.",
        help: "A first aid kit matters more than an AED here.",
        treatment: "Cool water first. Do not improvise products.",
        ongoing: "After cooling and covering, keep checking pain and changes.",
      },
      tags: ["burn", "hand", "blisters"],
    },
    {
      id: "heat_exhaustion",
      title: "Heat exhaustion",
      prompt:
        "During an outdoor shift, a patron is pale, sweaty, dizzy, and tired after being in the heat. They are awake and able to answer questions.",
      stages: withSubmit([
        stage("primary", commonPrimary),
        stage("abc", ["check_airway_breathing", "check_circulation_life_threats", "check_skin"]),
        stage("help", commonHelp),
        stage("treatment", [
          "move_cooler_area",
          "loosen_heavy_gear",
          "sips_fluid_awake",
          "wet_skin_fan",
          "cold_packs_core",
        ]),
        stage("ongoing", ["check_skin", "pulse_breathing_rate", "ask_sample", "reassess_treatment", "monitor_until_help", "leave_alone"]),
      ]),
      recommendedSequence: [
        "scene_safety",
        "ppe_barriers",
        "check_responsiveness",
        "check_airway_breathing",
        "move_cooler_area",
        "loosen_heavy_gear",
        "sips_fluid_awake",
        "get_backup",
        "check_skin",
        "reassess_treatment",
        "monitor_until_help",
      ],
      criticalActions: [
        "scene_safety",
        "check_responsiveness",
        "check_airway_breathing",
        "move_cooler_area",
        "loosen_heavy_gear",
        "reassess_treatment",
      ],
      weakActions: ["cold_packs_core"],
      dangerousActions: ["leave_alone", "water_unresponsive"],
      optionalGoodActions: [
        "ppe_barriers",
        "sips_fluid_awake",
        "get_backup",
        "wet_skin_fan",
        "check_skin",
        "monitor_until_help",
      ],
      actionFeedback: {
        move_cooler_area: "They are out of direct heat.",
        loosen_heavy_gear: "Extra heat-trapping gear is loosened or removed.",
        sips_fluid_awake: "They take small sips because they are awake and able.",
        wet_skin_fan: "Cooling has started and you keep reassessing.",
        leave_alone: "Their symptoms could get worse without monitoring.",
      },
      suggestedOrderText: "",
      hints: {
        primary: "They can talk, but still do your opening checks.",
        abc: "Look for worsening signs that could change this into a bigger emergency.",
        help: "Backup helps if symptoms worsen.",
        treatment: "Move them out of heat and start gentle cooling.",
        ongoing: "Keep checking if they improve or slide toward heat stroke signs.",
      },
      tags: ["heat", "awake", "dizzy"],
    },
    {
      id: "heat_stroke_suspicion",
      title: "Heat stroke suspicion",
      prompt:
        "A patron has been in the sun and is now confused, very hot, and not acting normally. You suspect severe heat illness.",
      stages: withSubmit([
        stage("primary", commonPrimary),
        stage("abc", ["check_airway_breathing", "check_circulation_life_threats", "check_skin"]),
        stage("help", commonHelp),
        stage("treatment", [
          "move_cooler_area",
          "loosen_heavy_gear",
          "wet_skin_fan",
          "cold_packs_core",
          "sips_fluid_awake",
          "fan_only",
          "water_unresponsive",
        ]),
        stage("ongoing", ["check_skin", "pulse_breathing_rate", "reassess_treatment", "monitor_until_help", "leave_alone"]),
      ]),
      recommendedSequence: [
        "scene_safety",
        "ppe_barriers",
        "check_responsiveness",
        "check_airway_breathing",
        "call_ems_911",
        "get_backup",
        "move_cooler_area",
        "loosen_heavy_gear",
        "wet_skin_fan",
        "cold_packs_core",
        "reassess_treatment",
        "monitor_until_help",
      ],
      criticalActions: [
        "scene_safety",
        "check_responsiveness",
        "check_airway_breathing",
        "call_ems_911",
        "move_cooler_area",
        "loosen_heavy_gear",
        "wet_skin_fan",
        "cold_packs_core",
        "monitor_until_help",
      ],
      weakActions: ["sips_fluid_awake", "fan_only"],
      dangerousActions: ["water_unresponsive", "leave_alone"],
      optionalGoodActions: ["ppe_barriers", "get_backup", "get_first_aid_kit", "check_skin", "reassess_treatment"],
      actionFeedback: {
        check_responsiveness: "They are confused and not acting normally.",
        call_ems_911: "Emergency help is being called for severe heat illness.",
        move_cooler_area: "They are moved out of direct heat.",
        wet_skin_fan: "Active cooling has started.",
        cold_packs_core: "Cold packs are applied to core areas.",
        sips_fluid_awake: "They are confused, so drinking may not be safe.",
        fan_only: "They are still confused and very hot.",
        water_unresponsive: "They may not be able to swallow safely.",
      },
      suggestedOrderText: "",
      hints: {
        primary: "Confusion is a big clue. Start fast but do not skip basics.",
        abc: "Check breathing and signs of a life threat.",
        help: "This is the heat illness scenario where EMS matters early.",
        treatment: "Fan-only is not enough. Think active cooling.",
        ongoing: "Keep cooling and reassessing while waiting for help.",
      },
      tags: ["heat", "confused", "serious"],
    },
  ];

  for (const scenario of scenarios) {
    scenario.suggestedOrderText = labelsFor(scenario.recommendedSequence);
  }

  window.POOL_DECK_DATA = {
    actions,
    scenarios,
    stageDefinitions,
  };
})();
